package com.example.miniproyecto4.view;

import com.example.miniproyecto4.model.Coordinate;

/**
 * Defines the callback methods used to notify mouse interactions
 * performed on the cells of a game board. Implementations of this
 * interface can respond to click and hover events generated by
 * individual board cells.
 *
 * @author Alejandro Valencia Sandoval
 * @author Maria Alejandra Pizarro Sarria
 */
public interface BoardInteractionListener
{
    /**
     * Called when a board cell is clicked.
     *
     * @param coordinate the coordinate of the clicked cell.
     */
    void onCellClicked(Coordinate coordinate);

    /**
     * Called when the mouse pointer enters a board cell.
     *
     * @param coordinate the coordinate of the cell entered.
     */
    void onCellHoverEntered(Coordinate coordinate);

    /**
     * Called when the mouse pointer leaves a board cell.
     *
     * @param coordinate the coordinate of the cell exited.
     */
    void onCellHoverExited(Coordinate coordinate);
}